title: Jeonghyeon Park
description: "Jeonghyeon Park's profile"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: jhparkinglot@gmail.com 
github_username: jhparkland
instagram_username: jh_parkland
linkedin_username: jeonghyeon-park
# facebook_username: facebook

# External API
giscus_repo: "jhparkland/profile"
giscus_repoId: "R_kgDOMEIV8w"
giscus_category: "General"
giscus_categoryId: "DIC_kwDOMEIV884Cf0Cz"
goatcounter_code: jhpark
google_analytics: G-FYBENFYX3J

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true